# 판다스(Pandas)

# 1. 판다스 설치

In [2]:
# 판다스 불러오기
import pandas as pd

import numpy as np

In [6]:
test_np = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
])
print(test_np)
print(test_np[0])
print(test_np.mean(axis=0))

test_pd = pd.DataFrame(test_np)
print(test_pd)
print(test_pd[0])
print(test_pd.mean(axis=0))



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[1 2 3 4]
[5. 6. 7. 8.]
   0   1   2   3
0  1   2   3   4
1  5   6   7   8
2  9  10  11  12
0    1
1    5
2    9
Name: 0, dtype: int64
0    5.0
1    6.0
2    7.0
3    8.0
dtype: float64


# 2. 시리즈(Series)

## 1) 생성 및 조회

<table>
    <thead>
        <tr>
            <th>이름</th><th>나이</th><th>키</th>
        </tr>
    </thead>
    <tbody>
        <tr><td>김영철</td><td>24</td><td>179.4</td></tr>
        <tr><td>송윤지</td><td>31</td><td>161.0</td></tr>
        <tr><td>임수현</td><td>26</td><td>174</td></tr>
    </tbody>
</table>

### (1) 데이터만 생성

In [ ]:
# 이름 열을 시리즈로 생성, 리스트로 작성해보세요



In [ ]:
# 이름 시리즈의 데이터 타입 조회

In [ ]:
# 나이 열을 시리즈로 생성, 튜플로 작성해보세요

In [ ]:
# 나이 시리즈의 데이터 타입 조회

In [ ]:
# 키 열을 시리즈로 생성, 넘파이로 작성해보세요

In [ ]:
# 키 시리즈의 데이터 타입 조회

In [ ]:
# 키 시리즈에 인덱스를 이름으로 추가

In [ ]:
# 시리즈 이름 추가

### (2) 인덱스와 함께 생성

In [ ]:
# 인덱스가 이름인 나이 시리즈를 생성 I - 튜플로 생성

In [ ]:
# 인덱스가 이름인 나이 시리즈를 생성 I - 딕셔너리로 생성

In [ ]:
# 나이 시리즈의 인덱스를 출력

In [ ]:
# 나이 시리즈의 값들만 출력

## 2) 연산

In [ ]:
# 데이터가 10, 20, 30인 시리즈 생성

In [ ]:
# 데이터가 1, 2, 3인 시리즈 생성

In [ ]:
# 사칙 연산 + 몫, 나머지, 제곱 넣어보기

## 3) 결측치

### (1) 결측치 발생

In [ ]:
# 데이터가 10, 20, 30인 시리즈 생성

In [ ]:
# 데이터가 1, 2, 3, 4인 시리즈 생성

In [ ]:
# 데이터 연산

예제
* 데이터가 10, 20, 30인 시리즈 생성, 인덱스는 부산, 울산, 대구으로 설정
* 데이터가 1, 2, 3, 4인 시리즈 생성, 인덱스는 광주, 부산, 울산, 대구으로 설정
* 데이터의 덧셈

In [ ]:
# 데이터가 10, 20, 30인 시리즈 생성

In [ ]:
# 데이터가 1, 2, 3, 4인 시리즈 생성

### (2) 결측치 파악

In [ ]:
# 전체 정보 조회로 파악하기

In [ ]:
# 조건문으로 판단하기

In [ ]:
# 결측치 개수 계산하기

### (3) 결측치 채우기

In [ ]:
# 데이터 출력하기

In [ ]:
# 결측값 채우기(fillna)

### (4) 결측치 삭제

In [ ]:
# 데이터 출력하기

In [ ]:
# 결측치 삭제(dropna)

In [ ]:
# 데이터 출력하기

In [ ]:
# 결측치 삭제한 내용을 원본 데이터에 그대로 반영하기

In [ ]:
# 결측치 삭제한 내용을 원본 데이터에 그대로 반영하기(inplace)

## 4) 통계

In [ ]:
# 데이터가 10, 20, 30인 시리즈 생성


In [ ]:
# 직접 계산하기

In [ ]:
# 요약하기

예제. 문자 데이터

```
['HR', 'Engineering', 'HR', 'Engineering', 'HR', 'Marketing', 'Engineering', 'Marketing', 'HR']
```