### Pytorch Tutorial

In [2]:
import torch

print(torch.__version__)
print(torch.cuda.is_available())

2.6.0+cu124
True


In [9]:
import numpy as np

a_numpy = np.array([5, 3, 1])
a = torch.tensor(a_numpy)

print(a[0])
print(a[0].item())

tensor(5)
5


In [20]:
b = torch.tensor([5, 3, 1])
c = torch.tensor([
    [[2, 3], [4, 6]],
    [[1, 3], [6, 2]],
    [[5, 2], [1, 3]]
])
print(b)
print(b[0])
print(b[0].item())

print(c)
print(c.ndim)
print(c.shape)
print(c.dtype)

tensor([5, 3, 1])
tensor(5)
5
tensor([[[2, 3],
         [4, 6]],

        [[1, 3],
         [6, 2]],

        [[5, 2],
         [1, 3]]])
3
torch.Size([3, 2, 2])
torch.int64


In [30]:
# 모든 원소가 0인 텐서 만들기 zeros
print(torch.zeros(3, 2, 4))

# 모든 원소가 1인 텐서 만들기 ones
print(torch.ones(3, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


In [47]:
# arange
a = torch.arange(0, 10)
print(a)
a = a.reshape(5, 2)
print(a)

a = a.reshape(2, -1)
print(a)

a = a.reshape(-1, 5)
print(a)

a = a.view(2, 5)
print(a)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])
tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


In [57]:
# 0에서 1까지를 10등분하고 싶을 때
a = torch.linspace(0, 1, 10)
print(a)

# 난수 만들기(rand, randn)
a = torch.rand(10)  # 0 ~ 1 사이 값
print(a)
a = torch.randn(10)  # normalization - 평균이 0이고 표준편차가 1인 값
print(a)

tensor([0.0000, 0.1111, 0.2222, 0.3333, 0.4444, 0.5556, 0.6667, 0.7778, 0.8889,
        1.0000])
tensor([0.4771, 0.2343, 0.4423, 0.2613, 0.7313, 0.7407, 0.5298, 0.7221, 0.0588,
        0.7160])
tensor([-0.7057,  0.9663,  0.8445,  1.1460,  0.2819, -1.4766, -0.1627,  0.4917,
        -0.4338, -0.1205])


In [62]:
# 미분하기
x = torch.tensor(2.0, requires_grad=True)  # requires_grad의 의미: 이 x는 변수입니다
y = x**3
print(x)
print(y)

y.backward()  # 미분해주세요 (dy/dx)
print(x.grad)


tensor(2., requires_grad=True)
tensor(8., grad_fn=<PowBackward0>)
tensor(12.)


In [64]:
# 미션: y = x^3 + 2x + 1, x=-2 일때의 미분값을 구하시오
x = torch.tensor(-2.0, requires_grad=True)
y = x**3 + 2*x + 1

print(x)
print(y)

y.backward()  # 미분해주세요
print(x.grad)

tensor(-2., requires_grad=True)
tensor(-11., grad_fn=<AddBackward0>)
tensor(14.)


In [66]:
x = torch.tensor(2.0, requires_grad=True)
y = 3 * x**2
z = 5 * y

z.backward()
print(x.grad)


tensor(60.)


### 행렬

In [18]:
# 미션
# 1. shape가 100, 5인 난수 tensor 생성(uniform 분포)
a = torch.rand(100, 5) 
# print(a)

# 2. 0부터 1까지 일정한 간격으로 100개인 tensor 생성
b = torch.linspace(0, 1, 100)
# print(b)

# 3. 모든 원소가 0인 100, 5 tensor 생성
c = torch.zeros(100, 5)
# print(c)

# 4. 원소의 shape가 1이고 원소가 1, 2, 3, 4, 5인 tensor 생성
d = torch.tensor([1, 2, 3, 4, 5])
print(d)
print(d.shape)

d_1 = torch.tensor([[1, 2, 3, 4, 5]])
print(d_1)
print(d_1.shape)

# 5. 0부터 9까지의 tensor 생성
e = torch.arange(0, 10)
print(e)

# 6. 5번을 (2, 5) shape로 바꾸기 (1. view, 2. reshape) 
f = e.reshape(2, 5)
print(f)

g = e.view(2, 5)
print(g)

tensor([1, 2, 3, 4, 5])
torch.Size([5])
tensor([[1, 2, 3, 4, 5]])
torch.Size([1, 5])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


In [21]:
A = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])

B = torch.tensor([
    [1, -1],
    [2, -2],
    [3, -3]
])

# 행렬의 곱셈 연산기호 @

print(A@B)
print(A.matmul(B))

tensor([[ 14, -14],
        [ 32, -32]])
tensor([[ 14, -14],
        [ 32, -32]])


In [20]:
A = torch.tensor([[1, -2, 3], [-4, 5, 6]])

# A의 모든 원소에 절대값 취하기
print(torch.abs(A))
print(A.abs())

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 2, 3],
        [4, 5, 6]])


### 이미지 형태

In [34]:
from PIL import Image
import numpy as np

png_file = "./파이리.png"

# PNG → JPG 변환
with Image.open(png_file) as img:
    # PNG의 투명도(Alpha) 채널 제거 후 RGB로 변환
    rgb_img = img.convert('RGB')
    rgb_img.save("./파이리.jpeg", format='JPEG')



In [42]:
image = Image.open("./파이리.jpeg")

image_arr = np.array(image)
print(image_arr.shape)



(724, 800, 3)


In [29]:
from torchvision import transforms

transform = transforms.ToTensor()
image_torch = transform(image)
print(image_torch.shape)


torch.Size([3, 724, 800])


In [41]:
image_arr[1]

array([[255, 255, 255],
       [255, 255, 255],
       [255, 255, 255],
       ...,
       [255, 255, 255],
       [255, 255, 255],
       [255, 255, 255]], dtype=uint8)

In [38]:
image_torch[1][300]

tensor([0.1922, 0.1922, 0.1922, 0.1922, 0.1922, 0.1922, 0.1922, 0.1922, 0.1922,
        0.1922, 0.1922, 0.1922, 0.1922, 0.1922, 0.1922, 0.1922, 0.1922, 0.1922,
        0.1922, 0.1922, 0.1922, 0.1922, 0.1922, 0.1922, 0.1922, 0.1922, 0.1922,
        0.1922, 0.1922, 0.1922, 0.1922, 0.1922, 0.1843, 0.1882, 0.2000, 0.1961,
        0.1843, 0.2667, 0.5882, 0.5882, 0.5882, 0.5804, 0.5647, 0.5686, 0.5882,
        0.5922, 0.5725, 0.5647, 0.5725, 0.5765, 0.5765, 0.5765, 0.5765, 0.5765,
        0.5765, 0.5765, 0.5765, 0.5765, 0.5765, 0.5765, 0.5765, 0.5765, 0.5765,
        0.5765, 0.5765, 0.5765, 0.5765, 0.5765, 0.5765, 0.5765, 0.5765, 0.5765,
        0.5765, 0.5765, 0.5765, 0.5765, 0.5765, 0.5765, 0.5765, 0.5765, 0.5765,
        0.5765, 0.5765, 0.5765, 0.5765, 0.5765, 0.5765, 0.5765, 0.5765, 0.5765,
        0.5765, 0.5765, 0.5765, 0.5765, 0.5765, 0.5765, 0.5765, 0.5765, 0.5765,
        0.5765, 0.5765, 0.5765, 0.5765, 0.5765, 0.5765, 0.5765, 0.5765, 0.5765,
        0.5765, 0.5765, 0.5765, 0.5765, 

### tensor 처리

In [46]:
# cat
# stack
data1 = torch.rand(4, 2)
data2 = torch.rand(4, 2)

result1 = torch.cat((data1, data2), dim=0)
result2 = torch.cat((data1, data2), dim=1)
result3 = torch.stack((data1, data2))

print(result1)
print(result2)
print(result3)

tensor([[0.9509, 0.0214],
        [0.5043, 0.1763],
        [0.5355, 0.1687],
        [0.2157, 0.2707],
        [0.8322, 0.6596],
        [0.2282, 0.5486],
        [0.7742, 0.2160],
        [0.0341, 0.5456]])
tensor([[0.9509, 0.0214, 0.8322, 0.6596],
        [0.5043, 0.1763, 0.2282, 0.5486],
        [0.5355, 0.1687, 0.7742, 0.2160],
        [0.2157, 0.2707, 0.0341, 0.5456]])
tensor([[[0.9509, 0.0214],
         [0.5043, 0.1763],
         [0.5355, 0.1687],
         [0.2157, 0.2707]],

        [[0.8322, 0.6596],
         [0.2282, 0.5486],
         [0.7742, 0.2160],
         [0.0341, 0.5456]]])


In [55]:
# 차원 추가 및 제거
A = torch.rand(3, 1, 2)
B = torch.rand(2, 5)
# squeeze: 크기가 1인 불필요 차원 제거
# unsqueeze: 크기가 1인 차원 생성
print(A.shape, A)
print(A.squeeze(0).shape, A.squeeze(0))  # 차원 제거 실패 (크기가 1이 아님)
print(A.squeeze(1).shape, A.squeeze(1))  # 두 번째 차원 제거 (크기가 1)
print(B.unsqueeze(1).shape, B.unsqueeze(1))  # 두 번째 차원에 크기가 1인 차원 추가


torch.Size([3, 1, 2]) tensor([[[0.0244, 0.5429]],

        [[0.9868, 0.0167]],

        [[0.7621, 0.2759]]])
torch.Size([3, 1, 2]) tensor([[[0.0244, 0.5429]],

        [[0.9868, 0.0167]],

        [[0.7621, 0.2759]]])
torch.Size([3, 2]) tensor([[0.0244, 0.5429],
        [0.9868, 0.0167],
        [0.7621, 0.2759]])
torch.Size([2, 1, 5]) tensor([[[0.6733, 0.2294, 0.3466, 0.6683, 0.2050]],

        [[0.8346, 0.9273, 0.9255, 0.8117, 0.5567]]])
