### Pytorch Tutorial

In [4]:
import torch

print(torch.__version__)
print(torch.cuda.is_available())

2.6.0+cu124
True


In [9]:
import numpy as np

a_numpy = np.array([5, 3, 1])
a = torch.tensor(a_numpy)

print(a[0])
print(a[0].item())

tensor(5)
5


In [20]:
b = torch.tensor([5, 3, 1])
c = torch.tensor([
    [[2, 3], [4, 6]],
    [[1, 3], [6, 2]],
    [[5, 2], [1, 3]]
])
print(b)
print(b[0])
print(b[0].item())

print(c)
print(c.ndim)
print(c.shape)
print(c.dtype)

tensor([5, 3, 1])
tensor(5)
5
tensor([[[2, 3],
         [4, 6]],

        [[1, 3],
         [6, 2]],

        [[5, 2],
         [1, 3]]])
3
torch.Size([3, 2, 2])
torch.int64


In [30]:
# 모든 원소가 0인 텐서 만들기 zeros
print(torch.zeros(3, 2, 4))

# 모든 원소가 1인 텐서 만들기 ones
print(torch.ones(3, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


In [47]:
# arange
a = torch.arange(0, 10)
print(a)
a = a.reshape(5, 2)
print(a)

a = a.reshape(2, -1)
print(a)

a = a.reshape(-1, 5)
print(a)

a = a.view(2, 5)
print(a)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])
tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


In [57]:
# 0에서 1까지를 10등분하고 싶을 때
a = torch.linspace(0, 1, 10)
print(a)

# 난수 만들기(rand, randn)
a = torch.rand(10)  # 0 ~ 1 사이 값
print(a)
a = torch.randn(10)  # normalization - 평균이 0이고 표준편차가 1인 값
print(a)

tensor([0.0000, 0.1111, 0.2222, 0.3333, 0.4444, 0.5556, 0.6667, 0.7778, 0.8889,
        1.0000])
tensor([0.4771, 0.2343, 0.4423, 0.2613, 0.7313, 0.7407, 0.5298, 0.7221, 0.0588,
        0.7160])
tensor([-0.7057,  0.9663,  0.8445,  1.1460,  0.2819, -1.4766, -0.1627,  0.4917,
        -0.4338, -0.1205])


In [62]:
# 미분하기
x = torch.tensor(2.0, requires_grad=True)  # requires_grad의 의미: 이 x는 변수입니다
y = x**3
print(x)
print(y)

y.backward()  # 미분해주세요 (dy/dx)
print(x.grad)


tensor(2., requires_grad=True)
tensor(8., grad_fn=<PowBackward0>)
tensor(12.)


In [64]:
# 미션: y = x^3 + 2x + 1, x=-2 일때의 미분값을 구하시오
x = torch.tensor(-2.0, requires_grad=True)
y = x**3 + 2*x + 1

print(x)
print(y)

y.backward()  # 미분해주세요
print(x.grad)

tensor(-2., requires_grad=True)
tensor(-11., grad_fn=<AddBackward0>)
tensor(14.)


In [66]:
x = torch.tensor(2.0, requires_grad=True)
y = 3 * x**2
z = 5 * y

z.backward()
print(x.grad)


tensor(60.)
